In [16]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [19]:
import numpy as np
word_embeddings = dict()
x=[]

with open('/content/drive/MyDrive/NLP/5111_4111Spring2023Shared-20230125T210009Z-001/5111_4111Spring2023Shared/Copy of glove.6B.50d.txt', encoding='utf-8') as f:
    for line in f:
        word = line.split()[0]
        x.append(word)
        embeddings = np.asarray(line.split()[1:], dtype='float32')
        word_embeddings[word] = embeddings


wrd = word_embeddings

In [20]:
from sklearn.metrics.pairwise import cosine_similarity


In [21]:
wrd["king"]-wrd["man"]+wrd["woman"]

array([ 0.41736597,  0.90427005, -1.0050299 , -0.06202102,  0.49725997,
        0.80667007, -0.14855   ,  0.80365   , -0.15653998, -0.66973996,
        0.23435399,  0.62476   ,  0.925871  , -0.97099996,  0.92566   ,
        0.89915   , -1.54596   , -0.52625   ,  0.13695401,  0.66199005,
        0.4871601 ,  0.37035   , -0.214214  ,  0.10100996,  0.71358   ,
       -2.0874999 , -1.1362001 , -1.1496099 , -0.53599   ,  0.27389997,
        1.6723    ,  0.02930999, -0.77656007,  0.46056286,  0.34866   ,
       -0.05741701,  0.19444   , -0.207748  , -0.73038995, -0.10751998,
        0.235544  ,  0.96423995, -0.46993998, -0.48727497, -0.25399995,
        0.4621299 , -0.66081   , -1.9451499 , -0.68797004, -0.49784005],
      dtype=float32)

In [22]:
sim_1 = cosine_similarity([wrd["king"]-wrd["man"]+wrd["woman"]], [wrd["queen"]])
print("king-man+woman and queen simlarity is:" ,sim_1)

king-man+woman and queen simlarity is: [[0.8609581]]


In [ ]:
x

In [ ]:
str = ' '.join(x)
str

In [25]:
import re


In [26]:
pattern = re.compile("go+p+i+")

In [27]:
print(pattern.search(str))

<re.Match object; span=(589082, 589086), match='gopi'>


In [31]:
wrd["gopi"]

array([ 0.16658 , -0.88233 , -0.7206  ,  1.1038  ,  0.60246 ,  1.2844  ,
        0.80683 ,  0.2833  , -0.74139 ,  0.80072 ,  0.15404 ,  0.70047 ,
        0.18268 ,  0.61171 ,  0.1344  , -0.37204 ,  1.103   ,  0.83918 ,
       -0.22356 , -0.05735 ,  0.65548 ,  0.95022 ,  0.55756 ,  0.56274 ,
        1.351   ,  1.1723  ,  0.93196 , -0.62185 , -1.0592  , -0.42793 ,
       -0.17345 , -0.39546 ,  0.1779  , -0.53025 , -0.32153 ,  0.32715 ,
       -0.32404 , -0.93926 ,  0.59944 ,  0.092959, -0.86525 ,  0.54341 ,
       -1.2014  , -0.19009 , -0.46569 , -0.53661 ,  0.2298  , -0.89066 ,
        0.86986 , -0.14541 ], dtype=float32)

In [32]:
sim_2 = cosine_similarity([wrd["king"]], [wrd["gopi"]])
sim_2

array([[-0.07374493]], dtype=float32)

In [33]:
sim_3 = cosine_similarity([wrd["queen"]], [wrd["gopi"]])
sim_3

array([[-0.03791821]], dtype=float32)